# Global configuration options. The `queue_ahead` and `tz` options can also be set on each task.
queue_ahead: 360 # Number of minutes to queue jobs into the future
queue_name: "default" # The Sidekiq queue name used by SimpleScheduler::FutureJob
tz: "America/New York" # The application time zone will be used by default if not set
#
# Runs once every 2 minutes starting at the top of the hour
simple_task:
  class: "CreatePairsJob"
  every: "2.minutes"
  at: "*:00"

## Runs once every week on Saturdays at 12:00 AM
weekly_task:
  class: "CreatePairsJob"
  every: "2.weeks"
  at: "Monday 9:00"
